name: release

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  create:

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace
    - name: "Rename archive"
      run: mv app/build/outputs/apk/debug/app-debug.apk app-release.apk
    - name: "Create GitHub release"
      uses: softprops/action-gh-release@v1
      with:
        files: app-release.apk
        fail_on_unmatched_files: true
