name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease --stacktrace
    - name: "Rename archive"
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
    - name: "Create GitHub release"
      uses: softprops/action-gh-release@v1
      with:
        files: app-release.apk
        fail_on_unmatched_files: true
